### ISSUE TITLE
Fix Methone login/user link with wrong color

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/cashflow#102]
Aurora overflows it some way

![image](https://user-images.githubusercontent.com/33149910/131254534-27070865-6fd8-4d10-b525-c23bbd2c9c5a.png)

![image](https://user-images.githubusercontent.com/33149910/131254550-2f0d5bc5-ce08-4a07-9019-4910cc5cf2f7.png)

![image](https://user-images.githubusercontent.com/33149910/131254655-75f0eb8b-72f1-477f-bd2c-8bfd10ecbce3.png)

**Comment by oskstr** [comment]
![Screenshot 2021-08-31 005725](https://user-images.githubusercontent.com/23638900/131417782-d8eb52d6-6067-4af6-9488-dced4e4bc7f3.png)

![Screenshot 2021-08-31 010049](https://user-images.githubusercontent.com/23638900/131417779-301d0d6f-10b3-471e-a833-6b7858e480f0.png)

First of all, hard to reproduce the issue. But I think it has to do with the styling of the styled component in Methone. 

It has a styling `all: unset` which includes `color: unset`  which I think is giving it a white color from the Methone theme's default contrast color by unsetting the Aurora specified `#757575`.  
```css
 color: ${({ theme }) => theme.primary.contrastText};
```

While the fix would probably work it would not respect the `contrastText` of the theme. 

But I'm pretty sure I have seen this issue myself once or twice and I have no clue why it is only happening sometimes.

**Comment by oskstr** [comment]
Fixed by datasektionen/Methone#27
