### ISSUE TITLE
Add ability to show statistics by year

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/cashflow#111]
Could be fun if you were able to choose which year to display in `/stats`
![image](https://user-images.githubusercontent.com/33149910/140298075-17e81e35-9742-4bdb-b6c1-a694fe2378cc.png)

Perhaps a select-element with different years. Is this implementable? @oskstr

**Comment by oskstr** [comment]
Certainly seems possible and very interesting 😄

**Comment by foodelevator** [comment]
The now closed #145 was a duplicate of this. Fixed in #168
