### ISSUE TITLE
Request: Add option to group "Betala" by bank account

### ISSUE THREAD

**Issue by tohanss** [datasektionen/cashflow#115]
So right now the "betala" page is grouped by "nämnd". It would be great to have an option to group by bank account, so that instead of "Filtrera på nämnd" showing every "nämnd" it would group all "nämnder" connected to the same account

![image](https://user-images.githubusercontent.com/66951210/143429196-3a0aa1b4-c259-45b1-a37e-e204c3c0c935.png)

Example:

```
Rewind
QN
Centralt
DKM
Informationsorganet
Demon
D-rektoratet
Mottagningen
```

Would become:

```
Rewind
Centralt
DKM
Mottagningen
```

**Comment by Herkarl** [comment]
https://www.w3schools.com/tags/tag_optgroup.asp
seems like a good start

**Comment by oskstr** [comment]
@tohanss Do you know where this information exist? Is there a link between "nämnd" and "bank account" somewhere?

**Comment by DouglasFischer** [comment]
Wont fix,
Bank accounts now heavily reduced
