### ISSUE TITLE
Vissa fakturor/utlägg kan inte tas bort ur systemet

### ISSUE THREAD

**Issue by Grunler** [datasektionen/cashflow#118]
Exempelvis: https://cashflow.datasektionen.se/invoices/139/

Det verkar bero på ett fel i:
https://github.com/datasektionen/cashflow/blob/master/expenses/views.py

HTTP-requesten skickas även om någonting är fel, vilket leder till att det blir ett fel i databasen.

**Comment by elmaxe** [comment]
Iom att det är en invoice borde det ske i: https://github.com/datasektionen/cashflow/blob/master/invoices/views.py

Vad säger @oskstr som har mer koll?

**Comment by elmaxe** [comment]
Vi lade till en feature som gör att man inte kan ta bort fakturor om något av följande är sant:
- fakturan är betald
- man inte är ägare av fakturan eller firmatecknare

**Comment by oskstr** [comment]
Till att börja med har jag inte admin-rättigheter så jag kan inte se fakturan i fråga.

Precis, för just invoice är det ju typ det här som händer (sammanfattat):
```python
# invoices/views.py
def delete_invoice(request, pk):
    invoice = Invoice.objects.get(pk=pk)
    may_delete_invoice = request.user.profile.may_delete_invoice(invoice)

    if not may_delete_invoice:
        return HttpResponseForbidden('Du har inte behörighet att ta bort denna faktura.')
    invoice.delete()
```

Sedan i `may_delete_invoice` är det typ som @elmaxe säger, men man kan också ta bort om man har attest-rätt på alla delar i fakturan. Men jag tror att det problematiska kan vara `is_payed`:

```python
# expenses/models.py
def may_delete_invoice(self, invoice):
    if invoice is None or invoice.is_payed():
        return False
   # ... massa andra cases

# invoices/models.py
def is_payed(self):
    if self.payed_at and self.payed_by:
        return True
    return False
```

Så om man gör något fel vid ny faktura med svaret om den är betald svarat typ "Ja, från sektionens konto" så verkar det som att man kanske inte kan radera den efter det. 

Jag vet ärligt talat inte vad som är bäst approach här. Just nu har vi ju satt att man inte ska kunna ta bort ett utlägg om det är utbetalt. I det fallet så behöver det ju redan bekräftat i pärmen, attesterat och sedan har någon klickat att de betalat ut den. Finns inte alls lika många sanity-checks för fakturor (fakturor gäller ju bara det sektionen har betalat eller ska betala, annars är det ett utlägg). 

Det borde rimligtvis vara något annat man kollar på när det gäller fakturor tror jag. Eller om typ firmatecknare alltid kan ta bort just fakturor.

**Comment by foodelevator** [comment]
Fixed in 3e6ff9cb9fd46da1b0fa750c926621bda7dfe347? Nä idk men har inte haft det här problemet på tillräckligt länge
