### ISSUE TITLE
Description can be longer than max description length in speedledger

### ISSUE THREAD

**Issue by dackebro** [datasektionen/cashflow#12]
Ser konstigt ut när man bokför och texten kapas av i speedledger

**Comment by bullfest** [comment]
Vad är maxlängden?

**Comment by bullfest** [comment]
Är typ villig att säga att det ändå är riimligt att det får vara lite kefft. Verifikatsnamnet behöver inte vara samma som kvittonamnet.
Det är ju bra att ha utförliga beskrivningar som gör det enklare att söka bland kvitton.
