### ISSUE TITLE
Utöka Kontonummer-fältet

### ISSUE THREAD

**Issue by Grunler** [datasektionen/cashflow#129]
Kontonummer-fältet verkar vara begränsat till 13 karaktärer på profilsidan. Det borde kanske utökas med ett par tecken.
Det verkar finnas några banker med 14 eller 15 siffror långa kontonummer:
https://web.archive.org/web/20221209045207/https://www.dbschenker.com/se-sv/haer-ser-du-hur-kontonumret-ska-skrivas-foer-olika-banker-481736

**Comment by foodelevator** [comment]
Siffrorna givna där gäller clearing+kontonummer. 13 tror jag räcker till endast kontonummer.

Har inte heller hört någon klaga och det känns som att jag borde hört det om det här var ett problem.
