### ISSUE TITLE
Ca2h.fl0w persists

### ISSUE THREAD

**Issue by augustjanse** [datasektionen/cashflow#13]
Ang. e789e9c finns ju namnet "Ca2h.fl0w" kvar på två ställen i samma fil, varav ett synligt. Om du nu skulle ta bort det, menar jag. Upp till dig.

Coolt system! Ser fram emot att lägga in KF-fikor 🎉

**Comment by bullfest** [comment]
Meh, skämtet kan få vara kvar lite. Ville mest inte ha det i rubriken för folk försökte gå in på "ca2h.fl0w.datasektionen.se".
