### ISSUE TITLE
Request: Krav på att utlägg ska vara nollskilda

### ISSUE THREAD

**Issue by Blytungdev** [datasektionen/cashflow#147]
Just nu verkar det gå att lägga in utlägg på 0kr. Det känns orimligt, det borde krävas minst 1 öre, annars är det väl inte ett utlägg? https://cashflow.datasektionen.se/expenses/10820/ är ett exempel på ett sådant utlägg som inte borde kunna skapas

**Comment by foodelevator** [comment]
Jag lyckas dock inte skapa utlägg utan att lägga till minst en kvittodel. Inte heller med kvittodelar där summan är 0. Så detta verkar snarare vara en bugg än en dålig feature. Däremot verkar backenden inte kolla detta, utan det görs endast i frontenden.

Jag antar att det vi kan testa är att kolla det i backenden också och se om det löser problemet.
