### ISSUE TITLE
Add copy buttons to accounting view

### ISSUE THREAD

**Issue by TerraDOOM** [datasektionen/cashflow#148]
Eller på svenska, lägg till knappar för bokföringsvyn. En knapp per kvitto i listan
![Screenshot_954](https://github.com/datasektionen/cashflow/assets/19736163/d7630d25-f8a8-4181-87f0-4e89d8665425)
såsom i screenshottet. Det som kopieras ska vara siffran i paranteserna till vänster och totala summan.

@Frequinzy

**Comment by Frequinzy** [comment]
Helst ska både text och nummer kopieras på vänster. Men texten är viktigare
