### ISSUE TITLE
Problem with choosing organs for payments

### ISSUE THREAD

**Issue by 98andwin** [datasektionen/cashflow#160]
[ENG] When trying to select which organ to put the reciept while on the phone, it doesn't allow me to choose any of the three options. They come up but are not selectable.

[SWE] Kan inte välja vilken nämnd på kvittodelen, det kommer upp (nämnder, projekt och övrigt) men ingen är valbar.

Environment: Chrome, android

**Comment by foodelevator** [comment]
Har du testat att vänta lite längre? Det är vad som visas innan nämnderna laddas in och det tar skitlång tid för att budgetsystemet är sämst.

**Comment by 98andwin** [comment]
Wow, okej du hade faktiskt rätt. Dock att det ska ta 15 sekunder innan allt visas 🙃

**Comment by foodelevator** [comment]
Kul va? :upside_down_face:
