### ISSUE TITLE
Formatera kontonummer

### ISSUE THREAD

**Issue by Lulcaz** [datasektionen/cashflow#178]
Kontonummer tillhörande Handelsbanken bör inte innehålla mellanslag för att göra det lättare att kopiera in i överförning till annans konto i Handelsbanken.
Kontonummer ska inte heller innehålla clearingnummer.

**Comment by foodelevator** [comment]
Man skriver ju in clearingnumret i rutan precis över kontonumret. Är det så att folk skriver in clearingnumret i båda rutorna eller konkatenerar cashflow ihop dem?

Grov skill issue av handelsbanken att inte ta bort mellanrum automatiskt när ni gör betalningar, men det borde ju gå rätt lätt att ta bort dem i cashflow.

**Comment by Lulcaz** [comment]
Ja, clearingnummret står som en del av kontonumret hos vissa banker, så folk glömmer att ta bort dem.

**Comment by foodelevator** [comment]
Okej så då är det väl rimligt att skriva tydligt på kontonummer-fältet att det inte ska innehålla clearingnummret.
Om det är möjligt att avgöra om clearingnumret står där eller inte på något bra sett kan man kanske också göra det till ett error om man råkat göra fel också.
