### ISSUE TITLE
Uploading a new image to a payment fails

### ISSUE THREAD

**Issue by Oxel40** [datasektionen/cashflow#200]
When editing an already created payment, uploading a new file for the receipt fails silently and no image is attached to the payment.

Steps to recreate:
1. create a payment with a receipt.
2. edit the payment
3. remove the previous image
4. upload another (fails silently with code 500 in the background)
5. save the changes, no picture is attached to the payment anymore.

Logged failure when uploading a new file:
![image](https://github.com/user-attachments/assets/d52e1a37-f93b-4762-ba2b-ae9dbe2408b9)

Perhaps related to: 
https://github.com/datasektionen/cashflow/issues/197
https://github.com/datasektionen/cashflow/issues/58

**Comment by foodelevator** [comment]
Seems

**Comment by foodelevator** [comment]
Seems like i only updated the `new` template when i made some changes to file uploads. Should be fixed now
