### ISSUE TITLE
The page you were looking for cannot be served - Cashflow

### ISSUE THREAD

**Issue by meurling** [datasektionen/cashflow#29]
När Olivia Herber skulle göra ett nytt utlägg på Cashflow och trycker på "Lägg till kvitto" får hon upp "The page you were looking for cannot be served". 

Är det Jonas snöflingor som spökar? :octopus:

**Comment by meurling** [comment]
Löste det genom att göra filen mindre, vore nice med ett sånt error-meddelande? :)

**Comment by jonasdahl** [comment]
@addem1234 @Plongy Hur gör man så att man kan ladda upp stora fina filer i dokku? Flyttade från sips till mjukglass, måste varit där det skiljer i inställningar.

**Comment by bullfest** [comment]
Ingen aning, är @addem1234 som löste det för mig på sips. Han har koll :)

**Comment by jonasdahl** [comment]
Det verkar inte lösa problemet att sätta client_max_body_size till 100M iaf. Kan det vara filöverföringen till S3 som knasar?

**Comment by jonasdahl** [comment]
Vilket var det @addem1234 gjorde på sips, ska nämnas.

**Comment by jonasdahl** [comment]
Verkar vara löst efter flytten tillbaka till sips
