### ISSUE TITLE
Bugg för utlägg inom beslutspengar(?)

### ISSUE THREAD

**Issue by enimstad** [datasektionen/cashflow#31]
Jag har försökt lägga in ett kvitto som ska gå på beslutspengar. Bilden tror jag inte är för stor o det ges inget felmeddelande, men när jag går o kollar /user/nimstad/receipts/ så ser jag att summan för kvittot hamnat på 0kr och det har autoattesterats. 

Gissar att det kan bero på att Beslutspengar inte har något sekundärt resultatställe eller sub-budgetpost.

**Comment by jonasdahl** [comment]
Man måste typ alltid ange resultatställe och budgetpost i Cashflow som det är just nu. Beslutspengar kanske borde ha ett Övrigt-resultatställe och Övrigt-budgetpost för att slippa hålla på i budgetsystemet varje gång någonting ska köpas in där, så lägger in det tillsvidare. 

Däremot hade det ju varit schysst med ett felmeddelande och lite validering, så skapar ett nytt issue för det.
