### ISSUE TITLE
Bokföringsrättigheter tar inte hänsyn till wildcard-*

### ISSUE THREAD

**Issue by sleeplesslord** [datasektionen/cashflow#48]
Jag kan inte bokföra det här kvittot: https://cashflow.datasektionen.se/expenses/802/
Detta trots att jag har wildcard bokföringsrättighet

**Comment by jonasdahl** [comment]
Fortfarande inte löst, så öppnar igen

**Comment by bullfest** [comment]
attest-* har aldrig funnits. Råkat lägga in det på någon grupp i början när jag la in första rättigheterna i plz, men iden kastades ut under första veckan av utveckling.

**Comment by bullfest** [comment]
Men borde bara vara att ändra denna metod https://github.com/datasektionen/cashflow/blob/master/expenses/models.py#L100

**Comment by sleeplesslord** [comment]
Det är bokföringsrättigheter som spökar, inte attest

**Comment by bullfest** [comment]
Jaha, den raden är ju uppenbart fel... Det borde vara `'accounting-*'` och inte bara `'*'`
