### ISSUE TITLE
"Administrera" shows up when user doesn't have any extra permissions

### ISSUE THREAD

**Issue by Sebberh** [datasektionen/cashflow#50]
Clicking on Administrera on the Home-page gives you an 404 error(and a willhelm-scream(no joke)). 
<img width="1439" alt="1" src="https://user-images.githubusercontent.com/34154689/36646388-2f9ae30e-1a77-11e8-9fb9-f141327f2d7f.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/34154689/36646390-31a10642-1a77-11e8-9eab-e480306aadf1.png">

**Comment by bullfest** [comment]
The wilhelm scream is 100% a feature.

As you don't have any permissions to do any administrative tasks (attest/pay out etc.) the "Administrera" button shouldn't even show up, so this is definently a bug in the ui.
