### ISSUE TITLE
remove Wilhelm-Scream from 404

### ISSUE THREAD

**Issue by nejlika** [datasektionen/cashflow#53]
Contributes nothing, is only annoying.

**Comment by jonasdahl** [comment]
+1

**Comment by bullfest** [comment]
I guess, was originally just a fun easteregg during development, which I forgot to remove before production.

Have had some people think it's a bit fun, but if people find it annoying then it should definently be removed.

**Comment by jonasdahl** [comment]
Jag tror du kommenterade bort den innan produktion, men jag la tillbaka den för ett tag sen 😂 🤛
