### ISSUE TITLE
Förbättra synligheten för ta-bort-kvitto-knappen

### ISSUE THREAD

**Issue by elinkas** [datasektionen/cashflow#54]
Går inte att ta bort poster man råkat lägga upp med felaktig info.

**Comment by jonasdahl** [comment]
Jag kan ta bort, men det kanske är för att jag har adminaccess? Vad händer om du går in på https://cashflow.datasektionen.se/expenses/[DITT_KVITTO-ID]/delete/?

**Comment by elinkas** [comment]
404 sidan finns inte för mig. Kan du som admin hjälpa mig att bort?

**Comment by jonasdahl** [comment]
Antar att det är det här du vill ta bort?
https://cashflow.datasektionen.se/expenses/1083/

Och du har testat 
https://cashflow.datasektionen.se/expenses/1083/delete?

Bekräfta så kan jag lösa

**Comment by jonasdahl** [comment]
Och den här kanske?
https://cashflow.datasektionen.se/expenses/1054/

**Comment by elinkas** [comment]
Det funkar med /delete! (sorry var lite snabb innan), Så man kan ta bort själv, så jag gör det. :D tack!
Skulle va najs med en Delete-knapp dock ;)

**Comment by jonasdahl** [comment]
Det ska finnas en på kvittosidan, men den är lite dold. Bör ligga längst ner i "Information"-tabellen.
