### ISSUE TITLE
Sortera kvitton på datum

### ISSUE THREAD

**Issue by jonasdahl** [datasektionen/cashflow#60]

**Comment by oskstr** [comment]
Beror på var man menar att kvitton ska sorteras efter datum men expenses är numera sorterade efter datum i bokföringsvyn genom #85 .

**Comment by elmaxe** [comment]
I `Attestera` sorteras kvitton numera efter ID stigande och i andra hand datum stigande
I `Lista utlägg` sorteras kvitton efter ID fallande och i andra hand datum fallande

Sedan #123
