### ISSUE TITLE
Indikator om det är ett digitalt kvittot eller ej

### ISSUE THREAD

**Issue by gustavung** [datasektionen/cashflow#63]
Jag skulle gärna vilja ha någon form av indikator om ett kvitto är digitalt eller inte när jag bekräftar kvitton i pärmen. Det är lätt att missta ett digitalt kvitto för ett kvitto som inte finns i pärmen.

**Comment by oskstr** [comment]
Det kanske finns en quick fix för det här - den skulle nog inte vara hundraprocentig men man skulle kunna använda: 
om ingen av filerna i ett utlägg `is_image` så är det iaf mer sannolikt att det är ett digitalt kvitto. 

Den funktionen är basically regex matchning på extension: `.*\.(jpg|jpeg|png|gif|bmp)`

Det kan bli false positives på typ iPhones HEIC-bilder som inte är bilder enligt den funktionen - men det skulle ju också vara lätt att kolla för.

**Comment by foodelevator** [comment]
Closed in #167
