### ISSUE TITLE
Går ej att välja någon nämnd i dropdown:en

### ISSUE THREAD

**Issue by karolinvalaszkai** [datasektionen/cashflow#72]

**Comment by bullfest** [comment]
Testa att ladda om sidan... Den datan hämtas från en separat service, kan vara att den svarade långsamt...

**Comment by karolinvalaszkai** [comment]
![61146737_359686261197482_2685968956602187776_n](https://user-images.githubusercontent.com/35804035/58083049-8958ae00-7bb8-11e9-86b9-f9833b7ab175.jpg)

**Comment by karolinvalaszkai** [comment]
Ser ut såhär nu istället, den laddar aldrig klart..

**Comment by bullfest** [comment]
Men vafan...
Vad sitter du i för mobilbrowser?

**Comment by karolinvalaszkai** [comment]
Safari i mobilen, men funkar inte på datorn med Chrome heller..

**Comment by bullfest** [comment]
Har försökt på en handfull enheter, en de som aldrig varit inne på cashflow förut och lyckas inte återskapa problemet :/

**Comment by karolinvalaszkai** [comment]
Ok, skulle ni kunna mata in mina uppgifter? Det är samma uppgifter som gäller för mitt tidigare utlägg som betalats
