### ISSUE TITLE
"Kvittodelar"-avsnittet laddar ej när man redigerar ett utlägg

### ISSUE THREAD

**Issue by henkejo** [datasektionen/cashflow#73]
Tänkte korrigera datum på ett utlägg:

**Gjort:**
Öppnar ett utlägg (https://cashflow.datasektionen.se/expenses/3230/)
Trycker på "Redigera kvitto"

**Händer:**
Under rubriken "Kvittodelar" står det "Laddar..." och knappen "Spara och redigera kvitto" är avaktiverad. Detta fortsätter oavsett hur länge jag väntar.
Skärmdump: https://i.imgur.com/hQJllbx.png

**Förväntat:**
Att alternativen och innehållet under "Kvittodelar" ska ladda och att jag ska kunna spara mina ändringar.

Jag kör Mac OS X och har provat med både Firefox och Chrome samt båda utan några tillägg.

**Comment by gustavung** [comment]
Jag gissar på att CF har detta beteende p.g.a. att budgetsystemet är nere just nu.

**Comment by bullfest** [comment]
Najs buggrapport, men det lär vara som @Guaschman säger. Testa igen nu när det är uppe igen :)
