### ISSUE TITLE
Stöd för HEIC/HEIF-bilder

### ISSUE THREAD

**Issue by klaraesr** [datasektionen/cashflow#78]
iPhones .HEIC-bilder syns inte direkt i Cashflow när man ska attestera, vore grymt med stöd/konvertering av dessa. 

![image](https://user-images.githubusercontent.com/34240897/75675633-cc879780-5c87-11ea-97a2-532582fe0032.png)

**Comment by bullfest** [comment]
:hankey: :apple:
Webbläsare har inte stöd för formatet som det ser ut.
Känner mig inte jättesugen på att skriva något som konverterar bara för äppliga format.

Verkar finnas lite webbläsar-plugins som försöker lösa detta, typ denna: https://chrome.google.com/webstore/detail/heic-image-viewer-decoder/apejnnfdjjgeohjlhieneeookfeomdhj
Har du möjlighet att testa vore ju det trevligt :smiley:

**Comment by Herkarl** [comment]
Solved by #165
