### ISSUE TITLE
Clicking 'Lista verifikat' from the admin view seems to cause a crash

### ISSUE THREAD

**Issue by oskstr** [datasektionen/cashflow#81]
Managed to reproduce a couple of times. 

**Steps:** 
- Click `Administrera` in top nav bar
- Click `Lista verifikat` under `Övrigt` in the side bar

**Behaviour:**
- Long load and then 504, gateway timeout error.

**Expected behaviour:**
- Show a list of verifikat

Might be caused by too much data in the response. Possible fix is to introduce pagination to that page if that is the cause.

**Comment by einbergisak** [comment]
Problemet är kvar ett år senare. Stötte nyss på det jag med :)

Sidan ligger då nere i några minuter för alla, inte bara lokalt.

**Comment by oskstr** [comment]
@einbergisak En PR skulle nog uppskattas här om du har lust att slänga ihop något. Det borde inte vara jättekomplicerat eftersom man löst samma problem på de flesta andra ställena redan, typ för expenses. Best practice här vore nog att dela upp datan på flera sidor.

Här borde vara funktionen du vill uppdatera: https://github.com/datasektionen/cashflow/blob/5b656b5a19a3748aadd8cb07d503c7b3c244db7c/admin/views.py#L368-L373

Som du ser hämtas allt. Men för att lista expenses så görs det i chunks av 25 st per sida:
https://github.com/datasektionen/cashflow/blob/5b656b5a19a3748aadd8cb07d503c7b3c244db7c/admin/views.py#L264-L288

Motsvarande görs för users och invoices. 

Sen behöver man nog också uppdatera själva vyn: [templates/admin/list-verification.html](https://github.com/datasektionen/cashflow/blob/master/templates/admin/list-verification.html)

Det borde även här bara vara att jämföra hur man gjort på andra ställen, typ expenses/users:

[templates/admin/expenses/overview.html](https://github.com/datasektionen/cashflow/blob/master/templates/admin/expenses/overview.html)

[templates/admin/users/overview.html](https://github.com/datasektionen/cashflow/blob/master/templates/admin/users/overview.html)

**Comment by einbergisak** [comment]
Blir svårt för mig att "slänga ihop nått", men du verkar för övrigt ha koll på vad som behöver göras, så det kanske är nått som du vill åtgärda? 😅😂

**Comment by oskstr** [comment]
Haha, svårt att fixa grejer med den inställningen 😂 Jag har tyvärr både ganska fullt upp och problem att köra cashflow lokalt av nån anledning. Jag har dessutom inte längre access att se sidan i fråga 😅 Men jag svarar gärna på frågor

Det här är nog faktiskt ett ganska bra issue om man är intresserad av att börja hjälpa till med underhåll av våra system. Det är ett problem som rör både vy och databas men det finns redan flera exempel i koden som kan guida en med hur man kan gå tillväga.

Det är nog många av oss som brukar sitta med det här som inte har så långt kvar på studierna. Jag började själv bli aktiv när jag sa till dåvarande d-sys att jag sett en bug och fick svaret att jag skulle "Skicka en PR" 😅 vilket jag gjorde.

Det är ju inget farligt om du skulle göra något fel på vägen och du får nog ganska bra koll på hur cashflow funkar. If you're up for the challenge, @einbergisak ? 😉

**Comment by einbergisak** [comment]
Haha ja vi får se asså, har rätt mycket i plugget just nu och jag var väl inte jättesugen 😂
Man kanske får ett ryck nån gång i framtiden, men det är inget jag vill sätta mig med just nu 😅

**Comment by oskstr** [comment]
Låter jättebra, tror inte det är jätteakut 👍
