### ISSUE TITLE
GUI-bugg med markeringsknapp

### ISSUE THREAD

**Issue by ghost** [datasektionen/cashflow#92]
Knappen för att markera utlägg 'i pärmen' dyker upp på samtliga utlägg och går att klicka på för mig, vilket gör att det då står "Förnamn Efternamn (d mmmm YYYY)" (som att det gått igenom). Däremot blir kvittot inte bekräftat på riktigt och uppdaterar jag sidan kommer knappen tillbaka.

Jag tillhör användargrupperna cashflow.revisorer, cashflow.NLG-cash samt cashflow.spexcash.

**Comment by oskstr** [comment]
Utan att ha satt in mig jättemycket i det här så verkar det vara Bekräfta-knappar visas för admins, admins defineras som:
```python
def is_admin(self):
    self.may_attest() or self.may_pay() or self.may_confirm() or self.may_account()
```
fast `may_confirm` är det som nog faktiskt bestämmer vilka som får bekräfta som är från `confirm`-rättigheten från pls.

**Comment by ghost** [comment]
Verkar funka nu.
