### ISSUE TITLE
No calendar widget shows up on receipt registration page

### ISSUE THREAD

**Issue by louisehellberg** [datasektionen/cashflow#96]
Hejsan, jag får server error när jag försöker registrera mitt kvitto!

**Comment by elmaxe** [comment]
Kan du beskriva felet mer i detalj? Får du fortfarande problem?

**Comment by bullfest** [comment]
Kikat i loggar, var `ValueError: time data '15 oktober' does not match format '%Y-%m-%d'` på denna rad
https://github.com/datasektionen/cashflow/blob/5b656b5a19a3748aadd8cb07d503c7b3c244db7c/expenses/views.py#L28

**Comment by bullfest** [comment]
Väldigt oklart hur `expense-date` har blivit `"15 oktober"`... 

@louisehellberg, när du ska fylla i "Transaktionsdatum", får du upp en datum-widget (som en kalender där man väljer datum)?
Vad använder du för webbläsare? :smiley:

**Comment by louisehellberg** [comment]
Hej, nej jag får inte upp en sådan kalender! Jag skrev med bokstäver på månaden så är säkert det som blir fel då ☺️
Med vänlig hälsning,
Louise

**Comment by bullfest** [comment]
Vad använder du för webbläsare? Låter som att det är något knasigt med vår frontend. Tills detta är fixat kan du i varje fall ange datum på formatet `åååå-mm-dd` (ex. `2020-11-23`)

**Comment by foodelevator** [comment]
Låter som ett webbläsarissue
